### ISSUE TITLE
Error in Colab Demo

### ISSUE THREAD

**Issue by SunnyHaze** [YuQiao0303/PointDreamer#2]
Hi! Thanks for your outstanding project!

I am running your demo on Colab but encountering some issues. Here is the stack of the problem.

```
start import
/usr/local/lib/python3.10/dist-packages/torch/utils/cpp_extension.py:1967: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation. 
If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].
  warnings.warn(
finish import
logfile output/2024.10.05.20.22.44_log.log
2024-10-06 04:22:44,863 -  Loading inpainter...
2024-10-06 04:22:55,122 -  inpainter loaded
2024-10-06 04:22:55,240 -  Loading POCO...
2024-10-06 04:22:55,423 -  InterpNet - Simple - K=64
2024-10-06 04:22:55,426 -  Network -- backbone -- 12783956 parameters
2024-10-06 04:22:55,426 -  Network -- projection -- 6498 parameters
  0% 0/1 [00:00<?, ?it/s]2024-10-06 04:22:55,739 -  Start Recon dataset/demo_data/clock.ply...
2024-10-06 04:22:55,758 -  Get Geometry by POCO...
2024-10-06 04:22:55,760 -  Submanifold sampling
2024-10-06 04:23:16,236 -  20.47657060623169
2024-10-06 04:23:16,238 -  Get Geometry time: 20.479620456695557 s by POCO
2024-10-06 04:23:16,238 -  UV Unwrapping by xatlas...
2024-10-06 04:23:16,238 -  Conducting UV Unwrapping...
2024-10-06 04:23:17,445 -  xatlas time: 1.2069709300994873 s
2024-10-06 04:23:17,445 -  Generate texture by PointDreamer...
0 / 8 inpainting time 23.38785743713379 s
1 / 8 inpainting time 22.262680530548096 s
2 / 8 inpainting time 22.994296073913574 s
3 / 8 inpainting time 23.27156925201416 s
4 / 8 inpainting time 22.902345180511475 s
5 / 8 inpainting time 22.830206632614136 s
6 / 8 inpainting time 23.04562735557556 s
7 / 8 inpainting time 23.059256315231323 s
inpainting time 183.75383877754211 s for 8 images
/usr/local/lib/python3.10/dist-packages/torch/functional.py:512: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3587.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
  0% 0/1 [03:31<?, ?it/s]
Traceback (most recent call last):
  File "/content/PointDreamer/demo.py", line 490, in <module>
    recon_one_textured_mesh(cfg,inpainter,POCO_net,camera_info, pc_file,name)
  File "/content/PointDreamer/demo.py", line 453, in recon_one_textured_mesh
    vertices,uvs,faces,mesh_tex_idx,atlas_img,mask = colorize_one_mesh(xyz,rgb,vertices,faces,f_normals,
  File "/content/PointDreamer/demo.py", line 197, in colorize_one_mesh
    atlas_img = paint_invisible_areas_by_neighbors(
  File "/content/PointDreamer/pointdreamer/unproject.py", line 138, in paint_invisible_areas_by_neighbors
    valid_index = torch.arange(len(subdivided_vertices))[subdevided_vert_has_color]
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)
```

Do you have any clue about it? There may be some other problem with this ipynb demo. Could you please run the collab demo from scratch from beginning to end to eliminate dependency bugs and problems? That will be of great help. Thank you very much.

**Comment by YuQiao0303** [comment]
Hi! I've updated the code and run the Colab demo from scratch, which works.
Hope this helps.

**Comment by SunnyHaze** [comment]
Thanks for your prompt response. However, I have reached the daily limited quota for Colab. I will try the code once my quota recovers and respond to you.

**Comment by SunnyHaze** [comment]
It works well! I will close this issue. 

Thank you very much!
